// Generated by tools/generate_frozen_mandarin.py. DO NOT EDIT BY HAND.
#ifndef CPP_PINYIN_FROZEN_MANDARIN_DATA_H
#define CPP_PINYIN_FROZEN_MANDARIN_DATA_H

#include <cstddef>
#include <cstdint>
#include <cpp-pinyin/PinyinGlobal.h>

namespace Pinyin { namespace FrozenData {
using PackedPinyin16 = std::uint16_t;
constexpr std::uint16_t kAsciiPairMask=0x5F1Fu;
constexpr std::uint16_t kAsciiPairRestore=0x2040u;
constexpr std::uint16_t kExtMask=0x8000u;
constexpr std::uint16_t kAltMask=0x2000u;
constexpr std::uint16_t kToneMask=0x00E0u;
constexpr std::uint8_t kBmpPageBase=0x30u;
constexpr std::uint8_t kBmpPageCount=0x70u;
constexpr std::uint16_t kDensePageMask=0x8000u;
constexpr std::uint8_t kInvalidFragment=0xFFu;

struct WordPair16 { std::uint16_t key; PackedPinyin16 pinyin; };
struct CandidateIndex16 { std::uint16_t codepoint; std::uint16_t desc; };
struct Pair16 { std::uint16_t from; std::uint16_t to; };

extern const std::uint16_t kWordPageOffset[112];
extern const std::uint8_t kWordPageCount[112];
extern const PackedPinyin16 kWordDense[18432];
extern const std::uint8_t kWordSparseLow[1463];
extern const PackedPinyin16 kWordSparsePinyin[1463];
extern const WordPair16 kWordExtra[1];
extern const WordPair16 kWordExt[473];
#if CPP_PINYIN_ENABLE_BIANG
extern const PackedPinyin16 kBiangPinyin;
#endif

extern const CandidateIndex16 kCandidateIndex[976];
extern const PackedPinyin16 kCandidatePool[1165];
extern const std::uint8_t kPolyPage[112];
extern const std::uint8_t kPolyBitmap[2496];

extern const std::uint32_t kPhrase2Keys[4095];
extern const std::uint16_t kPhrase2Desc[4095];
extern const PackedPinyin16 kPhrase2Override[4233];
extern const std::uint64_t kPhrase3Keys[1059];
extern const std::uint16_t kPhrase3Desc[1059];
extern const PackedPinyin16 kPhrase3Override[1178];
extern const std::uint64_t kPhrase4Keys[939];
extern const std::uint16_t kPhrase4Desc[939];
extern const PackedPinyin16 kPhrase4Override[1054];

#if CPP_PINYIN_ENABLE_TRADITIONAL
extern const Pair16 kTransBmpBmp[2997];
extern const Pair16 kTransBmpExt[364];
extern const Pair16 kTransExtBmp[14];
extern const Pair16 kTransExtExt[100];
#endif

extern const std::uint8_t kInitialId[64]; // direct byte offset into kInitialText
extern const std::uint8_t kFinalId[128];  // direct byte offset shared by all final pools
extern const char kInitialText[51];
extern const char kFinalBase[145];
extern const std::uint8_t kToneVowelUtf8[48];

/* Legacy tone-string layouts, retained for reference only:
extern const char kInitialText[kInitialCount][3];
extern const char kFinalBase[kFinalCount][5];
extern const std::uint8_t kFinalTone2Position[kFinalCount];
extern const char kFinalToneMarked[kFinalCount][4][6];
extern const char kFinalToneMarked1[145];
extern const char kFinalToneMarked2[145];
extern const char kFinalToneMarked3[145];
extern const char kFinalToneMarked4[145];
*/

constexpr std::size_t kWordExtraCount=1;
constexpr std::size_t kWordExtCount=473;
constexpr std::size_t kCandidateIndexCount=976;
constexpr std::size_t kPhrase2Count=4095;
constexpr std::size_t kPhrase3Count=1059;
constexpr std::size_t kPhrase4Count=939;
#if CPP_PINYIN_ENABLE_TRADITIONAL
constexpr std::size_t kTransBmpBmpCount=2997;
constexpr std::size_t kTransBmpExtCount=364;
constexpr std::size_t kTransExtBmpCount=14;
constexpr std::size_t kTransExtExtCount=100;
#endif
constexpr std::size_t kInitialCount=24;
constexpr std::size_t kFinalCount=34;

} }
#endif
